asyncapi: '2.6.0'
id: 'gotcha:websocket-api'
defaultContentType: application/json

info:
  title: Gotcha WebSocket API
  version: '1.0.0'
  description: |
    이 문서는 Gotcha 게임 플랫폼의 실시간 WebSocket(STOMP) 통신 명세서입니다.
    SockJS를 통해 WebSocket 연결을 시도합니다.

    | 주체             | 동작       | 사용하는 STOMP 함수       | 경로 예시              |
    |------------------|------------|---------------------------|-------------------------|
    | 클라이언트 → 서버 | 메시지 보냄 | `stompClient.send()`      | `/pub/**`      |
    | 서버 → 클라이언트 | 메시지 보냄 | `stompClient.subscribe()` | `/sub/**`         |

    ⭐[도메인 채널 prefix]
    -
    
    본 서비스는 총 4개의 메시지 전송 경로(prefix)를 사용하며, 구체적인 로직 분기는 경로가 아닌 DTO 필드로 구분됩니다. 

    - /pub/room/{roomId} : 대기방 관련 로직들 (대기방 내 채팅 포함)
    - /pub/chat/** : 채팅 관련 로직들 (전체 채팅 및 개인 채팅)
    - /pub/game/{roomId} : 게임 관련 로직들 
    - /pub/lobby/** : 로비 관련 로직들 

    ⭐[에러 채널]
    -

    - 대기방 에러 채널 : /user/room/errors/{userUuid}
    - 로비 에러 채널 : /user/lobby/errors/{userUuid}
    - 채팅 에러 채널 : /user/chat/errors/{userUuid}
    - 게임 에러 채널 : /user/game/errors/{userUuid}
    - 기본 에러 채널 : /user/queue/errors/{userUuid}



servers:
  production:
    url: http://43.203.244.35:8080/ws-connect
    protocol: ws
    description: >
      SockJS 기반 STOMP WebSocket 연결을 지원합니다.
      기본적으로 WebSocket(ws) 사용, 실패 시 HTTP long-polling 등 으로 fallback 됩니다.

      핸드쉐이크 시, 반드시 HTTP 헤더에
      Authorization: Bearer {JWT 토큰}
      를 포함해야 합니다.


channels:
  /user/queue/errors/{userUuid}:
    description: |
      도메인 에러 외 서버에서 발생된 에러 메시지를 수신하는 WebSocket 구독 채널입니다.
    parameters:
      userUuid:
        description: 에러 메시지를 수신할 사용자의 UUID
        schema:
          type: string
    subscribe:
      message:
        name: ExceptionResponse
        summary: 에러 응답 메시지
        payload:
          $ref: '#/components/schemas/ExceptionRes'

  /user/room/errors/{userUuid}:
    description: |
      대기방에서 발생한 에러 메시지를 수신하는 WebSocket 구독 채널입니다. (대기방 채팅에서 발생된 에러도 포함됩니다.)
    parameters:
      userUuid:
        description: 에러 메시지를 수신할 사용자의 UUID
        schema:
          type: string
    subscribe:
      message:
        name: ExceptionResponse
        summary: 에러 응답 메시지
        payload:
          $ref: '#/components/schemas/ExceptionRes'

  /user/game/errors/{userUuid}:
    description: |
      게임에서 발생한 에러 메시지를 수신하는 WebSocket 구독 채널입니다.
    parameters:
      userUuid:
        description: 에러 메시지를 수신할 사용자의 UUID
        schema:
          type: string
    subscribe:
      message:
        name: ExceptionResponse
        summary: 에러 응답 메시지
        payload:
          $ref: '#/components/schemas/ExceptionRes'

  /user/lobby/errors/{userUuid}:
    description: |
      로비에서 발생한 에러 메시지를 수신하는 WebSocket 구독 채널입니다.
    parameters:
      userUuid:
        description: 에러 메시지를 수신할 사용자의 UUID
        schema:
          type: string
    subscribe:
      message:
        name: ExceptionResponse
        summary: 에러 응답 메시지
        payload:
          $ref: '#/components/schemas/ExceptionRes'

  /user/chat/errors/{userUuid}:
    description: |
      채팅(전체체팅 및 개인 채팅)에서 발생한 에러 메시지를 수신하는 WebSocket 구독 채널입니다.
    parameters:
      userUuid:
        description: 에러 메시지를 수신할 사용자의 UUID
        schema:
          type: string
    subscribe:
      message:
        name: ExceptionResponse
        summary: 에러 응답 메시지
        payload:
          $ref: '#/components/schemas/ExceptionRes'

  /pub/lobby/create:
    description: 클라이언트가 새 방을 생성 요청하는 채널
    publish:
      message:
        payload:
          $ref: '#/components/schemas/CreateRoomRequest'

  /sub/lobby/create/{userUuid}:
    description: 클라이언트가 새 방을 생성 응답하는 채널
    parameters:
      userUuid:
        description: 사용자의 UUID
        schema:
          type: string
    subscribe:
      message:
        payload:
          $ref: '#/components/schemas/RoomIdRes'

  /pub/lobby/join/{roomId}:
    description: 클라이언트가 방에 참가 요청하는 채널
    parameters:
      roomId:
        description: 대기방의 고유 식별자
        schema:
          type: string
    publish:
      message:
        payload:
          $ref: '#/components/schemas/CreateRoomRequest'

  /sub/lobby/join/{userUuid}:
    description: 클라이언트가 방에 참가 응답 채널
    parameters:
      userUuid:
        description: 사용자의 UUID
        schema:
          type: string
    subscribe:
      message:
        payload:
          $ref: '#/components/schemas/RoomIdRes'

  /sub/lobby/list/event:
    description: 클라이언트가 대기방의 목록을 업데이트 하기 위해 이벤트 정보와 대기방의 요약 정보를 받아오는 채널
    subscribe:
      message:
        oneOf:
          - name: Room Create
            summary: 새로운 방 생성됨
            payload:
              $ref: '#/components/schemas/RedisResponse_RoomList_Create'

          - name: Room Update
            summary: 방 정보 수정됨
            payload:
              $ref: '#/components/schemas/RedisResponse_RoomList_Update'

          - name: Room Delete
            summary: 방 삭제됨
            payload:
              $ref: '#/components/schemas/RedisResponse_RoomList_Delete'

  /pub/room/{roomId}:
    description: |
      클라이언트가 대기방 내에서 발생 가능한 로직 요청을 전송하는 채널입니다.

      [사용 가능한 이벤트 타입]
      - CHAT: 대기방 채팅
      - READY: 준비
      - UNREADY: 준비 해제
      - EXIT: 방 퇴장
      - UPDATE: 방 정보 수정
      - START: 게임 시작
      - OWNER_CHANGE: 방장 권한 위임
      - KICK: 플레이어 강퇴

      `eventType` 값에 따라 content의 의미는 다르게 해석됩니다.
    parameters:
      roomId:
        description: 대상 대기방의 고유 ID
        schema:
          type: string
    publish:
      message:
        name: RoomEventRequest
        summary: 대기방 내 요청 이벤트 전송
        contentType: application/json
        payload:
          $ref: '#/components/schemas/RoomReq'

  /sub/room/{roomId}:
    description: |
      클라이언트가 대기방 내에서 발생 가능한 로직 처리 결과를 응답 받는 채널입니다.
    parameters:
      roomId:
        description: 대기방 고유 ID
        schema:
          type: string
    subscribe:
      message:
        oneOf:
          - name: ChatEvent
            summary: CHAT 이벤트 - 채팅 메시지 수신
            payload:
              $ref: '#/components/schemas/RedisResponse_RoomChat'

          - name: ReadyEvent
            summary: READY 이벤트 - 준비
            payload:
              $ref: '#/components/schemas/RedisResponse_RoomReady'

          - name: UnReadyEvent
            summary: UnREADY 이벤트 - 준비 해제
            payload:
              $ref: '#/components/schemas/RedisResponse_RoomUnReady'

          - name: ExitEvent
            summary: EXIT 이벤트 - 퇴장 정보
            payload:
              $ref: '#/components/schemas/RedisResponse_RoomExit'

          - name: StartEvent
            summary: START 이벤트 - 게임 시작 알림(게임 메타데이터 포함)
            payload:
              $ref: '#/components/schemas/RedisResponse_GameStart'

          - name: Room Update
            summary: UPDATE 이벤트 - 방정보 및 유저 리스트 반환
            payload:
              $ref: '#/components/schemas/RedisResponse_RoomList_Update'

  /pub/chat/all:
    description: 클라이언트가 전체 채팅 메시지를 전송하는 채널
    publish:
      message:
        payload:
          $ref: '#/components/schemas/RedisReq_AllChat'

  /sub/chat/all:
    description: 클라이언트가 전체 채팅 메시지를 수신하는 채널
    subscribe:
      message:
        name: AllChatMessage
        summary: 전체 채팅 메시지 수신
        payload:
          $ref: '#/components/schemas/RedisRes_AllChat'

  /pub/chat/private:
    description: 클라이언트가 특정 사용자에게 개인 채팅(귓속말) 메시지를 전송하는 채널입니다. `receiverUuid`에 수신 대상 사용자의 UUID를 지정하여 메시지를 전송합니다
    publish:
      message:
        payload:
          $ref: '#/components/schemas/RedisReq_PrivateChat'

  /sub/chat/private/{receiverId}:
    description: 개인 채팅 메시지를 수신하는 구독 채널입니다.
    parameters:
      receiverId:
        description: ID of the message receiver
        schema:
          type: string
    subscribe:
      message:
        name: PrivateMessage
        summary: 개인 채팅 메시지 수신
        payload:
          $ref: '#/components/schemas/RedisRes_PrivateChat'

  /pub/game/{roomId}:
    description: 클라이언트가 게임 내 이벤트를 전송하는 채널입니다. `eventType` 필드에 따라 서버가 게임 로직을 분기 처리합니다.
    parameters:
      roomId:
        description: 게임이 진행 중인 방의 고유 식별자
        schema:
          type: string
    publish:
      message:
        oneOf:
          - name: DrawingSubmitEvent
            summary: DRAWING_SUBMIT - 그림 URL 전송
            payload:
              $ref: '#/components/schemas/DrawingSubmitReq'

          - name: GuessSubmitEvent
            summary: GUESS_SUBMIT - 플레이어의 정답 시도 제출
            payload:
              $ref: '#/components/schemas/Guess'



  /sub/game/{roomId}:
    description: |
      게임 흐름 관련 메시지를 수신하는 구독 채널입니다.
      
      [ 발생 가능한 메시지 타입 ]
      
      - `ROUND_START`: 라운드의 시작을 알립니다. 
        - `payload`의 `data` 필드에는 해당 라운드의 메타정보(사용자 별 그려야 하는 제시어)를 알리기 위해 `Round` 타입이 전송됩니다.
      - `GUESS_START`: 추측 단계의 시작을 알립니다. 
        - `payload`의 `data` 필드에는 추측을 위한 정보들인 제시어 list가 전송됩니다. 
        - 클라이언트에서는 `drawerUuid` 필드와 `imageURL` 필드를 확인해 그림을 그린 플레이어와 그림을 맞출 플레이어를 구분할 수 있습니다.
      - `GUESS_REQUEST`: 추측 요청 브로드캐스트입니다. 
        - `payload`의 `data` 필드에는 추측을 위한 메타정보인 `guess` 데이터가 전송됩니다. 
        - `guesserUuid` 필드가 AI인 경우 잠시 후 AI 추측결과가 `GUESS_SUBMIT`으로 함께 브로드캐스트 됩니다. 
        - `guesserUuid` 필드가 AI가 아닌 경우 클라이언트에서 해당 `guesserUuid`의 `GUESS_SUBMIT`을 기다리게 됩니다.  
        - 또한 `endTime` 필드가 이벤트 발행 시점의 30초 후로 설정되며, 클라이언트에서는 이 시간 안에 `GUESS_SUBMIT`을 보내주어야 합니다. 
      - `GUESS_SUBMIT`:  추측 데이터 제출 브로드캐스트입니다. 
        - 해당 턴의 추측 데이터 제출 시 이를 브로드캐스트 합니다. 
        - `payload`의 `data` 필드에는 `Guess` 데이터가 전송됩니다. 
      - `GUESS_RESULT`: 추측 결과를 클라이언트에 브로드캐스트합니다.
        - `payload`의 `data` 필드에는 `guess` 데이터가 정답 여부와 함께 전송됩니다.
      - `SCORE_UPDATE`: 추측 성공 시 점수 현황을 업데이트 해주고, 이를 브로드캐스트 해줍니다. 
        - 추측 실패 시에는 전송되지 않습니다. 
        - `payload`의 `data` 필드에는 `Score` 데이터가 전송됩니다. 
      - `ROUND_END`: 해당 라운드의 종료를 알립니다.
        - 라운드 종료 시 해당 라운드의 결과를 포함한 라운드 데이터를 브로드캐스트 해줍니다. 
        - `payload`의 `data` 필드에는 `round` 데이터가 전송됩니다. 
      - `GAME_END`: 게임 종료 시 해당 게임의 결과를 포함한 게임 데이터를 브로드캐스트 해줍니다. 
        - `payload`의 `data` 필드에는 `game` 데이터가 전송됩니다. 

    parameters:
      roomId:
        description: 현재 게임이 진행 중인 방의 ID
        schema:
          type:
            string
    subscribe:
      message:
        oneOf:
          - name: ROUND_START
            payload:
              $ref: '#/components/schemas/RedisResponse_RoundStart'
          - name: GUESS_START
            payload:
              $ref: '#/components/schemas/RedisResponse_GuessStart'
          - name: GUESS_REQUEST
            payload:
              $ref: '#/components/schemas/RedisResponse_GuessRequest'
          - name: GUESS_SUBMIT
            payload:
              $ref: '#/components/schemas/RedisResponse_GuessSubmit'
          - name: GUESS_RESULT
            payload:
              $ref: '#/components/schemas/RedisResponse_GuessResult'
          - name: SCORE_UPDATE
            payload:
              $ref: "#/components/schemas/RedisResponse_ScoreUpdate"
          - name: ROUND_END
            payload:
              $ref: "#/components/schemas/RedisResponse_RoundEnd"
          - name: GAME_END
            payload:
              $ref: "#/components/schemas/RedisResponse_GameEnd"



components:

  schemas:
    ExceptionRes:
      type: object
      description: API 예외 응답 구조
      properties:
        code:
          type: string
          description: 에러 코드
        status:
          type: integer
          format: int32
          description: HTTP 상태 코드
        message:
          type: string
          description: 에러 메시지
        fields:
          type: object
          description: 필드별 상세 오류 메시지 (있을 경우)
          additionalProperties:
            type: string
      required:
        - code
        - status
        - message

    CreateRoomRequest:
      type: object
      required:
        - title
        - maxUser
        - hasPassword
        - difficulty
        - gameType
        - roundCount
      properties:
        title:
          type: string
          description: 제목 (필수 입력)

        maxUser:
          type: integer
          description: 최대 인원수 (필수 입력)

        hasPassword:
          type: boolean
          description: 비밀번호 사용 여부

        password:
          type: string
          description: 문자열이 숫자 4자리로만 구성되어 있어야 한다

        difficulty:
          type: string
          enum: [BASIC, ADVANCED]
          description: 인공지능 난이도 (필수)

        gameType:
          type: string
          enum: [TRICK_MYOMYO, LULU_ART_EXAM]
          description: 묘묘 - 2인 / 루루 - 1인 게임 모드

        roundCount:
          type: integer
          minimum: 1
          maximum: 5
          description: 라운드 수 (1~5 사이)

    RoomReq:
      type: object
      required:
        - eventType
      properties:
        eventType:
          type: string
          enum: [CHAT, READY, JOIN, EXIT, UNREADY, START, OWNER_CHANGE, KICK]
          description: |
            클라이언트가 수행하고자 하는 이벤트의 종류입니다.
        content:
          type: string
          description: |
            이벤트에 따라 의미가 달라지는 콘텐츠입니다.
            - CHAT: 채팅 메시지
            - JOIN: 비밀번호가 있는 대기방의 경우 비밀번호, 비밀번호가 없다면 안보내도 됩니다.
            - KICK: 강퇴하고자 하는 사용자의 UUID
            - UPDATE: 방의 정보(title, hasPassword, password, difficulty, roundCount)를 json문자열 형태로 보냅니다.
            - OWNER_CHANGE: 방장 권한을 위임하고자 하는 사용자의 UUID
            - 나머지는 content를 사용하지 않습니다.

    RedisResponse_RoomMetadata:
      type: object
      description: 방 생성/요청 응답용 Redis 메시지 (RoomMetadata 포함)
      properties:
        userId:
          type: string
          description: 메시지를 보낸 사용자 UUID
        topic:
          type: string
          description: Redis로 발행된 채널명
        payload:
          $ref: '#/components/schemas/RoomMetadata'

    RoomSummaryRes:
      type: object
      properties:
        roomId:
          type: string
          description: 방 ID
        title:
          type: string
          description: 방 제목
        owner:
          type: string
          description: 방장 닉네임
        hasPassword:
          type: boolean
          description: 비밀번호 사용 여부
        maxUser:
          type: integer
          description: 최대 인원 수
        currentUser:
          type: integer
          description: 현재 인원 수

    RoomMetadata:
      type: object
      properties:
        id:
          type: string
          description: 방 ID
        title:
          type: string
          description: 방 제목
        owner:
          type: string
          description: 방장 닉네임
        hasPassword:
          type: boolean
          description: 비밀번호 사용 여부
        password:
          type: string
          description: 비밀번호 (빈 문자열일 수 있음)
        max:
          type: integer
          description: 최대 인원 수
        min:
          type: integer
          description: 최소 인원 수
        aiLevel:
          type: string
          enum: [BASIC, ADVANCED]
          description: AI 난이도
        gameMode:
          type: string
          enum: [TRICK_MYOMYO, LULU_ART_EXAM]
          description: 게임 모드
        ownerUuid:
          type: string
          description: |
            이 방을 생성한 사용자의 UUID입니다.  
            클라이언트는 해당 값을 통해 수신된 방 정보가 본인이 생성한 것인지 식별할 수 있습니다.

    RedisResponse_RoomList_Create:
      type: object
      properties:
        userId:
          type: string
        topic:
          type: string
        payload:
          type: object
          properties:
            eventType:
              type: string
              enum: [CREATE]
            eventAt:
              type: string
              format: date-time
            data:
              $ref: '#/components/schemas/RoomSummaryRes'

    RedisResponse_RoomList_Update:
      type: object
      properties:
        userId:
          type: string
        topic:
          type: string
        payload:
          type: object
          properties:
            eventType:
              type: string
              enum: [ UPDATE ]
            eventAt:
              type: string
              format: date-time
            data:
              $ref: '#/components/schemas/RoomSummaryRes'

    RedisResponse_RoomList_Delete:
      type: object
      properties:
        userId:
          type: string
        topic:
          type: string
        payload:
          type: object
          properties:
            eventType:
              type: string
              enum: [ DELETE ]
            eventAt:
              type: string
              format: date-time
            data:
              $ref: '#/components/schemas/RoomSummaryRes'

    RedisResponse_RoomChat:
      type: object
      properties:
        userId:
          type: string
        topic:
          type: string
        payload:
          type: object
          properties:
            eventType:
              type: string
              enum: [CHAT]
            eventAt:
              type: string
              format: date-time
            data:
              $ref: '#/components/schemas/RoomChatMessage'

    RedisResponse_RoomJoin:
      type: object
      properties:
        userId:
          type: string
        topic:
          type: string
        payload:
          type: object
          properties:
            eventType:
              type: string
              enum: [JOIN]
            eventAt:
              type: string
              format: date-time
            data:
              type: array
              items:
                $ref: '#/components/schemas/RoomUserInfo'

    RedisResponse_RoomReady:
      type: object
      properties:
        userId:
          type: string
        topic:
          type: string
        payload:
          type: object
          properties:
            eventType:
              type: string
              enum: [ READY ]
            eventAt:
              type: string
              format: date-time
            data:
              type: string
              description: 레디를 한 사용자의 UUID

    RedisResponse_RoomUnReady:
      type: object
      properties:
        userId:
          type: string
        topic:
          type: string
        payload:
          type: object
          properties:
            eventType:
              type: string
              enum: [ UNREADY ]
            eventAt:
              type: string
              format: date-time
            data:
              type: string
              description: 레디 취소를 한 사용자의 UUID

    RedisResponse_RoomExit:
      type: object
      properties:
        userId:
          type: string
        topic:
          type: string
        payload:
          type: object
          properties:
            eventType:
              type: string
              enum: [ EXIT ]
            eventAt:
              type: string
              format: date-time
            data:
              type: string
              description: 퇴장한 사용자의 UUID

    RedisResponse_GameStart:
      type: object
      properties:
        userId:
          type: string
        topic:
          type: string
        payload:
          type: object
          properties:
            eventType:
              type: string
              enum: [START]
            eventAt:
              type: string
              format: date-time
            data:
              type: object
              $ref: '#/components/schemas/AISaysRes'

    AISaysRes:
      type: object
      description: 게임 시작 시 게임 메타 데이터와 게임 시작 시 AI 메시지를 함께 보내주기 위한 구조
      properties:
        gameData:
          type: object
          description: 게임 진행 중 발생하는 데이터가 전송됩니다(Game, Round, Word, Guess, GamePlayer).
          $ref: '#/components/schemas/Game'
        aiSays:
          type: string
          description: 게임 시작 시 AI의 메시지


    RedisResponse_RoundStart:
      type: object
      properties:
        userId:
          type: string
        topic:
          type: string
        payload:
          type: object
          properties:
            eventType:
              type: string
              enum: [ROUND_START]
            aiSays:
              type: string
              description: 게임 진행 중 AI에게서 오는 메시지입니다. AI에서 메시지가 오지 않는 이벤트 경우 "null" 값으로 오게 됩니다.
              example: "\"으.. 잠깐 오류가 났네. 다시 해볼게!\""
            data:
              type: object
              properties:
                roundIndex:
                  type: integer
                drawingEndTime:
                  type: string
                currentWordIndex:
                  type: integer
                roundWinner:
                  type: string
                  nullable: true
                  description: 해당 라운드의 Winner를 나타내는 필드입니다. ROUND_START 이벤트 발생 시에는 null로 반환됩니다.
              example:
                roundIndex: 1
                drawingEndTime: "2025-05-28T21:01:24.4270926"
                currentWordIndex: 0
                roundWinner: null
            endTime:
              type: string
              nullable: true
              example: null
            eventAt:
              type: string
              example: "2025-05-28T21:00:56.30379"

    RedisResponse_GuessStart:
      type: object
      properties:
        userId:
          type: string
        topic:
          type: string
        payload:
          type: object
          properties:
            eventType:
              type: string
              enum: [GUESS_START]
            data:
              type: array
              items:
                type: object
                properties:
                  wordIndex:
                    type: integer
                  word:
                    type: string
                  drawerUuid:
                    type: string
                  imageURL:
                    type: string
                  submitted:
                    type: boolean
              example:
                - wordIndex: 0
                  word: "syringe"
                  drawerUuid: "l3lwXGrb"
                  imageURL: "l3lwXGrb/9228e506-059c-4a0f-9874-65d68aff372b.png"
                  submitted: true
                - wordIndex: 1
                  word: "cooler"
                  drawerUuid: "z2E63KqK"
                  imageURL: "z2E63KqK/39caa311-8195-4f39-94d1-84ae4710b474.png"
                  submitted: true
            eventAt:
              type: string
              example: "2025-05-27T20:28:36.4511966"

    RedisResponse_GuessRequest:
      type: object
      properties:
        userId:
          type: string
        topic:
          type: string
        payload:
          type: object
          properties:
            eventType:
              type: string
              enum: [ GUESS_REQUEST ]
            data:
              type: object
              properties:
                guesserUuid:
                  type: string
                guessWord:
                  type: string
                  nullable: true
                attempts:
                  type: integer
                correct:
                  type: boolean
                  nullable: true
              example:
                guesserUuid: "AI"
                guessWord: null
                attempts: 1
                correct: null
            aiSays:
              type: string
              nullable: true
              example: null
            endTime:
              type: string
              nullable: true
              example: null
            eventAt:
              type: string
              example: "2025-05-31T22:17:36.8926635"


    RedisResponse_GameEnd:
      type: object
      properties:
        userId:
          type: string
        topic:
          type: string
        payload:
          type: object
          properties:
            eventType:
              type: string
              enum: [ GAME_END ]
            data:
              type: object
              properties:
                roomId:
                  type: string
                gameType:
                  type: string
                difficulty:
                  type: string
                gameStatus:
                  type: string
                  nullable: true
                currentRound:
                  type: integer
                totalRounds:
                  type: integer
                aiScore:
                  type: integer
                scores:
                  type: object
                  additionalProperties:
                    type: integer
                gamePlayers:
                  type: array
                  nullable: true
                  items:
                    type: object
                rounds:
                  type: array
                  items:
                    type: object
                    properties:
                      roundIndex:
                        type: integer
                      drawingEndTime:
                        type: string
                      roundWinner:
                        type: string
                        nullable: true
                      currentWordIndex:
                        type: integer
                      words:
                        type: array
                        items:
                          type: object
                          properties:
                            wordIndex:
                              type: integer
                            word:
                              type: string
                            drawerUuid:
                              type: string
                            submitted:
                              type: boolean
                            imageURL:
                              type: string
                            aiGuesses:
                              type: array
                              items:
                                type: object
                                properties:
                                  guesserUuid:
                                    type: string
                                  guessWord:
                                    type: string
                                  attempts:
                                    type: integer
                                  correct:
                                    type: boolean
                            playerGuesses:
                              type: array
                              items:
                                type: object
                                properties:
                                  guesserUuid:
                                    type: string
                                  guessWord:
                                    type: string
                                  attempts:
                                    type: integer
                                  correct:
                                    type: boolean
                            aiPredictions:
                              type: array
                              items:
                                type: object
                                properties:
                                  predicted:
                                    type: string
                                  confidence:
                                    type: number
                                    format: float
                      scores:
                        type: object
                        additionalProperties:
                          type: integer
                winner:
                  type: string
              example:
                roomId: "6483"
                gameType: "TRICK_MYOMYO"
                difficulty: "BASIC"
                gameStatus: null
                currentRound: 3
                totalRounds: 3
                aiScore: 0
                scores:
                  AI: 0
                  z2E63KqK: 3
                  l3lwXGrb: 6
                gamePlayers: null
                rounds:
                  - roundIndex: 1
                    drawingEndTime: "2025-05-28T21:01:24.4270926"
                    roundWinner: null
                    currentWordIndex: 2
                    words:
                      - wordIndex: 0
                        word: "sandwich"
                        drawerUuid: "l3lwXGrb"
                        submitted: true
                        imageURL: "https://gotchaai-image-bucket.s3.ap-northeast-2.amazonaws.com/l3lwXGrb/546258da-8e18-4792-8b35-5b8f8c92bcec.png"
                        aiGuesses:
                          - guesserUuid: "AI"
                            guessWord: "cat"
                            attempts: 1
                            correct: false
                        playerGuesses:
                          - guesserUuid: "z2E63KqK"
                            guessWord: "laptop"
                            attempts: 3
                            correct: false
                        aiPredictions:
                          - predicted: "cat"
                            confidence: 99.4355320930481
                          - predicted: "book"
                            confidence: 0.40926095098257065
                          - predicted: "calendar"
                            confidence: 0.06800925475545228
                    scores:
                      l3lwXGrb: 3
                  # ... (roundIndex 2, 3도 동일 구조)
                winner: "DRAW"
            aiSays:
              type: string
              example: "으.. 잠깐 오류가 났네. 다시 해볼게!"
            endTime:
              type: string
              nullable: true
              example: null
            eventAt:
              type: string
              example: "2025-05-28T21:02:41.1232855"

    RedisResponse_RoundEnd:
      type: object
      properties:
        userId:
          type: string
        topic:
          type: string
        payload:
          type: object
          properties:
            eventType:
              type: string
              enum: [ ROUND_END ]
            data:
              type: object
              properties:
                roundIndex:
                  type: integer
                drawingEndTime:
                  type: string
                roundWinner:
                  type: string
                currentWordIndex:
                  type: integer
                words:
                  type: array
                  items:
                    type: object
                    properties:
                      wordIndex:
                        type: integer
                      word:
                        type: string
                      drawerUuid:
                        type: string
                      submitted:
                        type: boolean
                      imageURL:
                        type: string
                      aiGuesses:
                        type: array
                        items:
                          type: object
                          properties:
                            guesserUuid:
                              type: string
                            guessWord:
                              type: string
                            attempts:
                              type: integer
                            correct:
                              type: boolean
                      playerGuesses:
                        type: array
                        items:
                          type: object
                          properties:
                            guesserUuid:
                              type: string
                            guessWord:
                              type: string
                            attempts:
                              type: integer
                            correct:
                              type: boolean
                      aiPredictions:
                        type: array
                        items:
                          type: object
                          properties:
                            predicted:
                              type: string
                            confidence:
                              type: number
                              format: float
                scores:
                  type: object
                  additionalProperties:
                    type: integer
              example:
                roundIndex: 2
                drawingEndTime: "2025-05-28T21:02:38.3805662"
                roundWinner: "PLAYER"
                currentWordIndex: 2
                words:
                  - wordIndex: 0
                    word: "drums"
                    drawerUuid: "l3lwXGrb"
                    submitted: true
                    imageURL: "https://gotchaai-image-bucket.s3.ap-northeast-2.amazonaws.com/l3lwXGrb/546258da-8e18-4792-8b35-5b8f8c92bcec.png"
                    aiGuesses:
                      - guesserUuid: "AI"
                        guessWord: "book"
                        attempts: 1
                        correct: false
                    playerGuesses:
                      - guesserUuid: "z2E63KqK"
                        guessWord: "drums"
                        attempts: 1
                        correct: true
                    aiPredictions:
                      - predicted: "book"
                        confidence: 75.47914385795593
                      - predicted: "calendar"
                        confidence: 11.874808371067047
                      - predicted: "cat"
                        confidence: 8.319798856973648
                  - wordIndex: 1
                    word: "sword"
                    drawerUuid: "z2E63KqK"
                    submitted: true
                    imageURL: "https://gotchaai-image-bucket.s3.ap-northeast-2.amazonaws.com/l3lwXGrb/546258da-8e18-4792-8b35-5b8f8c92bcec.png"
                    aiGuesses:
                      - guesserUuid: "AI"
                        guessWord: "cat"
                        attempts: 1
                        correct: false
                    playerGuesses:
                      - guesserUuid: "l3lwXGrb"
                        guessWord: "sword"
                        attempts: 1
                        correct: true
                    aiPredictions:
                      - predicted: "cat"
                        confidence: 91.84954762458801
                      - predicted: "calendar"
                        confidence: 6.590797007083893
                      - predicted: "book"
                        confidence: 0.9185523726046085
                scores:
                  z2E63KqK: 3
                  l3lwXGrb: 3
            aiSays:
              type: string
              example: "으.. 잠깐 오류가 났네. 다시 해볼게!"
            endTime:
              type: string
              nullable: true
              example: null
            eventAt:
              type: string
              example: "2025-05-28T21:02:41.1232855"

    RedisResponse_ScoreUpdate:
      type: object
      properties:
        userId:
          type: string
        topic:
          type: string
        payload:
          type: object
          properties:
            eventType:
              type: string
              enum: [ SCORE_UPDATE ]
            data:
              type: object
              additionalProperties:
                type: integer
              example:
                AI: 0
                z2E63KqK: 3
                l3lwXGrb: 3
            aiSays:
              type: string
              nullable: true
              example: null
            endTime:
              type: string
              nullable: true
              example: null
            eventAt:
              type: string
              example: "2025-05-28T21:02:39.2287028"


    RedisResponse_GuessResult:
      type: object
      properties:
        userId:
          type: string
        topic:
          type: string
        payload:
          type: object
          properties:
            eventType:
              type: string
              enum: [ GUESS_RESULT ]
            data:
              type: object
              properties:
                guesserUuid:
                  type: string
                guessWord:
                  type: string
                attempts:
                  type: integer
                correct:
                  type: boolean
              example:
                guesserUuid: "AI"
                guessWord: "book"
                attempts: 1
                correct: false
            aiSays:
              type: string
              example: "으.. 잠깐 오류가 났네. 다시 해볼게!"
            endTime:
              type: string
              nullable: true
              example: null
            eventAt:
              type: string
              example: "2025-05-28T21:02:20.4475533"

    RedisResponse_GuessSubmit:
      type: object
      properties:
        userId:
          type: string
        topic:
          type: string
        payload:
          type: object
          properties:
            eventType:
              type: string
              enum: [GUESS_SUBMIT]
            data:
              type: object
              properties:
                guesserUuid:
                  type: string
                guessWord:
                  type: string
                attempts:
                  type: integer
                correct:
                  type: boolean
                  nullable: true
              example:
                guesserUuid: "AI"
                guessWord: "book"
                attempts: 1
                correct: null
            aiSays:
              type: string
              example: "으.. 잠깐 오류가 났네. 다시 해볼게!"
            endTime:
              type: string
              nullable: true
              example: null
            eventAt:
              type: string
              example: "2025-05-28T21:02:18.3712128"
    AllChatMessage:
      type: object
      properties:
        nickname:
          type: string
        content:
          type: string
        chatType:
          type: string
          enum: [ALL]
        sentAt:
          type: string
          format: date-time

    PrivateChatMessage:
      type: object
      properties:
        nickname:
          type: string
        content:
          type: string
        chatType:
          type: string
          enum: [PRIVATE]
        sentAt:
          type: string
          format: date-time

    RoomChatMessage:
      type: object
      properties:
        nickname:
          type: string
        content:
          type: string
        chatType:
          type: string
          enum: [ROOM]
        sentAt:
          type: string
          format: date-time

    RoomUserInfo:
      type: object
      properties:
        userUuid:
          type: string
        nickname:
          type: string
        ready:
          type: boolean

    RedisReq_PrivateChat:
      type: object
      description: |
        채팅 메시지 전송 요청 객체입니다.
      properties:
        receiverUuid:
          type: string
          nullable: true
          description: |
            - 개인 채팅 시, `receiverUuid'는 필수입니다.
        content:
          type: string
          description: 메시지 내용
      required:
        - content

    RedisReq_AllChat:
      type: object
      description: |
        채팅 메시지 전송 요청 객체입니다.
      properties:
        content:
          type: string
          description: 메시지 내용
      required:
        - content

    RedisRes_AllChat:
      type: object
      description: |
        - 전체 채팅 메시지를 포함하는 Redis 전송 구조
        - 응답 시 ChatType은 ALL, ROOM, PRIVATE중 하나로 전송됩니다.
      properties:
        userId:
          type: string
          nullable: true
          description: null (전체 채팅이므로 사용자 구분 없음)
        topic:
          type: string
          description: Redis로 발행된 전체 채팅 채널명
        payload:
          $ref: '#/components/schemas/AllChatMessage'

    RedisRes_PrivateChat:
      type: object
      description: 특정 사용자에게 전송되는 개인 채팅 메시지 응답 구조입니다.
      properties:
        userId:
          type: string
          description: 수신 대상 사용자의 UUID입니다.
        topic:
          type: string
          description: Redis로 발행된 개인 채팅 채널명 (`/sub/chat/private/{receiverUuid}`)
        payload:
          $ref: '#/components/schemas/PrivateChatMessage'










    Game:
      type: object
      properties:
        roomId:
          type: string
          description: "게임 방의 고유 식별자"
          example: "9827"
        gameType:
          type: string
          description: "게임의 타입"
          enum: [ TRICK_MYOMYO, LULU_ART_EXAM ]
          example: "TRICK_MYOMYO"
        difficulty:
          type: string
          description: "게임 난이도"
          enum: [ BASIC, ADVANCED ]
          example: "BASIC"
        gameStatus:
          type: string
          description: "게임의 현재 상태"
          enum : [ GAME_STARTED, ROUND_STARTED, DRAWING_PHASE, GUESSING_PHASE, ROUND_ENDED, GAME_ENDED ]
        currentRound:
          type: integer
          description: "현재 라운드 번호 (0이면 아직 아무 라운드 시작하지 않음, 1부터 시작)"
          example: 0
        totalRounds:
          type: integer
          description: "전체 라운드 수"
          example: 3
        aiScore:
          type: integer
          description: "AI의 현재 점수"
          example: 0
        scores:
          type: object
          description: "게임 전체 참가자의 현재 점수"
          $ref: "#/components/schemas/Score"
        gamePlayers:
          type: array
          description: "게임에 참여 중인 플레이어 목록"
          items:
            $ref: '#/components/schemas/GamePlayer'
        rounds:
          type: array
          description: "게임의 라운드 정보 목록"
          items:
            $ref: '#/components/schemas/Round'
        winner:
          type: string
          description: "게임 최종 우승자 (playerUuid 또는 'AI' 또는 'players')"
          nullable: true
          example: "AI"



    GamePlayer:
      type: object
      properties:
        playerUuid:
          type: string
          description: "플레이어의 UUID"
          example: "l3lwXGrb"
        nickname:
          type: string
          description: "플레이어의 닉네임"
          example: "test1"

    Round:
      type: object
      properties:
        roundIndex:
          type: integer
          description: "라운드 번호 (0부터 시작)"
          example: 0
        drawingEndTime:
          type: string
          format: date-time
          nullable: true
          description: "그리기 종료 시간 (ISO 8601)"
          example: "null"
        roundWinner:
          type: string
          nullable: true
          description: "라운드 승리자 (playerUuid 또는 'AI' 또는 'players')"
          example: "null"
        currentWordIndex:
          type: integer
          description: "현재 추측중인 Word 인덱스"
          example: 0
        words:
          type: array
          description: "라운드에서 그릴/맞출 단어 목록"
          items:
            $ref: '#/components/schemas/Word'
    Word:
      type: object
      properties:
        wordIndex:
          type: integer
          description: "단어 인덱스"
          example: 0
        word:
          type: string
          description: "제시어"
          example: "bush"
        drawerUuid:
          type: string
          description: "그림을 그린 플레이어의 UUID"
          example: "l3lwXGrb"
        submitted:
          type: boolean
          description: "해당 그림이 제출되었는지 여부"
          example: false
        imageURL:
          type: string
          description: "해당 그림의 URL"
          example: "https://gotchaai-image-bucket.s3.ap-northeast-2.amazonaws.com/l3lwXGrb/546258da-8e18-4792-8b35-5b8f8c92bcec.png"
        aiGuesses:
          type: array
          description: "AI 플레이어의 추측 목록"
          items:
            $ref: '#/components/schemas/Guess'
        playerGuesses:
          type: array
          description: "사용자의 추측 목록"
          items:
            $ref: '#/components/schemas/Guess'
        aiPredictions:
          type: array
          description: "AI 모델의 분류 결과(상위 3개)"
          items:
            $ref: '#/components/schemas/AIPrediction'
    Guess:
      type: object
      properties:
        guesserUuid:
          type: string
          description: "추측을 시도한 플레이어의 UUID(AI일 경우 'AI')"
          example: "z2E63KqK"
        guessWord:
          type: string
          description: "플레이어의 추측 단어"
          example: "tree"
        attempts:
          type: integer
          description: "플레이어의 추측 시도 수"
          example: 1
        correct:
          type: boolean
          description: "플레이어의 추측 정답 여부"
          example: true


    AIPrediction:
      type: object
      properties:
        predicted:
          type: string
          description: "AI의 추측 단어"
          example: "apple"
        confidence:
          type: number
          format: float
          description: "AI 추측의 신뢰도 (0~1)"
          example: 0.85

    Score:
      type: object
      description: 유저별 점수, useruuid - score 형태의 Map
      additionalProperties:
        type: integer
        description: 획득한 점수
      example:
        AI: 0
        z2E63KqK: 3
        l3lwXGrb: 6

    RoomIdRes:
      type: object
      description: 방 ID를 반환하는 응답 객체
      properties:
        roomId:
          type: string
          description: 생성된 방의 고유 ID
      required:
        - roomId

    DrawingSubmitReq:
      type: object
      description: 그림 제출 요청
      properties:
        imageURL:
          type: string
          format: uri
          description: 업로드된 그림의 URL
      required:
        - imageURL
